### ISSUE TITLE
`@protected` keyword set to a string

### ISSUE THREAD

**Issue by timothee-haudebourg** [convenience-org/age-verification-context#10]
Hi, I'm unable to process the `age-v1` context because one `@protected` entry is set to a string instead of a boolean value here:
https://github.com/convenience-org/age-verification-context/blob/7d9396535129db6953fd6bb8b1165c47b0a10c66/contexts/age-v1.jsonld#L3

**Comment by davidlehn** [comment]
- Fixed in 6.0.0, along with a `contentHash` to `digestMultibase` change that was already present in the live context.
- This unscoped `age-verification-context` from this project is now deprecated in favor of `@digitalbazaar/age-verification-context`.  We had (mostly) moved over to that scoped package a long time ago and the npm deprecation notices should now improve that messaging.
- The boolean issue was copy & pasted to various contexts in various places and hopefully they are fixed now.
